version: '3.7'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: yarn start
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
    networks:
      - coffee-shop-ui
networks:
  coffee-shop-ui:
    name: coffee-shop-ui
