version: '3.7'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - '80:80'
    networks:
      - coffee-shop-ui
networks:
  coffee-shop-ui:
    name: coffee-shop-ui
